version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
     - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=furniture
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=minhkhanh2003

  adminer: 
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=db